import { AnalysisResult, QuestionOptions, UserError } from '../types';
import { tdkService } from './tdkService';

export const CANONICAL_TYT_CATEGORIES = ['Büyük Harflerin Yazımı','Bitişik Yazılan Birleşik Kelimeler','Ayrı Yazılan Kelimeler',"Bağlaç Olan Da / De'nin Yazımı","Bağlaç Olan Ki'nin Yazımı","Soru Eki Mı / Mi'nin Yazımı",'Kısaltmaların Yazımı','Tarih ve Sayıların Yazımı','Ses Olayları ve Yardımcı Fiiller','Düzeltme İşareti (Şapka ^)'] as const;
export type CanonicalCategory = typeof CANONICAL_TYT_CATEGORIES[number];
export function normalizeCategory(raw?: string): CanonicalCategory { const x=(raw||'').toLocaleLowerCase('tr-TR'); if(x.includes('büyük')||x.includes('unvan')||x.includes('kurum'))return 'Büyük Harflerin Yazımı'; if(x.includes('bitişik')||x.includes('birleşik'))return 'Bitişik Yazılan Birleşik Kelimeler'; if(x.includes('da / de')||x.includes('da bağlacı')||x.includes('de bağlacı'))return "Bağlaç Olan Da / De'nin Yazımı"; if(x.includes('ki bağlacı')||x.includes("ki'nin"))return "Bağlaç Olan Ki'nin Yazımı"; if(x.includes('soru eki')||x.includes('mı / mi'))return "Soru Eki Mı / Mi'nin Yazımı"; if(x.includes('kısaltma'))return 'Kısaltmaların Yazımı'; if(x.includes('tarih')||x.includes('sayı'))return 'Tarih ve Sayıların Yazımı'; if(x.includes('şapka')||x.includes('düzeltme'))return 'Düzeltme İşareti (Şapka ^)'; if(x.includes('ses')||x.includes('fiil')||x.includes('düşme')||x.includes('türeme'))return 'Ses Olayları ve Yardımcı Fiiller'; return x.includes('ayrı')||x.includes('ikileme')?'Ayrı Yazılan Kelimeler':'Ayrı Yazılan Kelimeler'; }
async function proxy(body: unknown){const r=await fetch('/.netlify/functions/ai-proxy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`AI HTTP ${r.status}`);return d;}
function valid(q:any,t:any){const ks=['A','B','C','D','E'];const w=String(q?.wrong_option||'').toUpperCase();return !!q?.options&&ks.every(k=>typeof q.options[k]==='string'&&q.options[k].trim())&&ks.includes(w)&&q.options[w].toLocaleLowerCase('tr-TR').includes(String(t.wrong_word).toLocaleLowerCase('tr-TR'))&&new Set(ks.map(k=>q.options[k].trim().toLocaleLowerCase('tr-TR'))).size===5;}
function localQ(t:any,i:number){const ks=['A','B','C','D','E'];const w=ks[i%5];const d=['Araştırmacılar yeni bulguları dikkatle değerlendirdi.','Yazar eserinde toplumun değişen değerlerini ele aldı.','Öğrenciler sınavdan sonra soruları birlikte inceledi.','Konuşmacı konunun ayrıntılarını örneklerle açıkladı.'];const o:any={};let n=0;ks.forEach(k=>o[k]=k===w?`Bu cümlede '${t.wrong_word}' kullanımı dikkat çekti.`:d[n++%4]);return {question_text:'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı yapılmıştır?',options:o,wrong_option:w,wrong_word:t.wrong_word,correct_word:t.correct_word,rule_category:normalizeCategory(t.category),explanation:`'${t.wrong_word}' yerine '${t.correct_word}' yazılmalıdır.`,coach_note:`Doğru yazılış: '${t.correct_word}'.`,difficulty_score:5};}
function sanitize(raw:any,text:string):AnalysisResult{const ks=['A','B','C','D','E'];const options:QuestionOptions={};ks.forEach(k=>{if(typeof raw?.options?.[k]==='string')options[k]=raw.options[k];});const w=String(raw?.wrong_option||'').toUpperCase();if(!ks.includes(w)||!raw?.wrong_word||!raw?.correct_word||Object.keys(options).length!==5)throw new Error('AI geçersiz analiz döndürdü.');const deterministic=tdkService.findErrorInOptions(options);const verified=deterministic&&deterministic.wrongOption===w?deterministic:null;return {question_text:typeof raw.question_text==='string'&&raw.question_text.trim()?raw.question_text.trim():text,options,wrong_option:w,wrong_word:verified?.wrongWord||String(raw.wrong_word),correct_word:verified?.correctWord||String(raw.correct_word),rule_category:verified?.category||normalizeCategory(raw.rule_category),explanation:verified?.explanation||String(raw.explanation||'Yazım kuralı analiz edildi.'),coach_note:verified?.coachNote||tdkService.sanitizeCoachNote(raw.coach_note,String(raw.wrong_word),String(raw.correct_word),normalizeCategory(raw.rule_category)),difficulty_score:Math.min(10,Math.max(1,Number(raw.difficulty_score)||5)};}
export const groqService={
 async analyzeTextWithLlama(raw:string,errors:UserError[]=[]):Promise<AnalysisResult>{const text=raw.trim();if(!text)throw new Error('Soru boş.');const d=await proxy({task:'analyze',text,existingUserErrors:errors.slice(0,20)});return sanitize(d.result,text);},
 async generateAIQuestionsBatch(targets:{wrong_word:string;correct_word:string;category:string}[],difficulty:'kolay'|'orta'|'zor',inspirationSnippets:string[]=[]):Promise<any[]>{const out:any[]=[];for(let i=0;i<targets.length;i+=3){const chunk=targets.slice(i,i+3);try{const d=await proxy({task:'generate',targets:chunk,difficulty,inspirationSnippets:inspirationSnippets.slice(0,6)});const received=Array.isArray(d.questions)?d.questions:[];chunk.forEach((t,j)=>{const idx=received.findIndex((q:any)=>valid(q,t));out.push(idx>=0?received[idx]:localQ(t,j));});}catch{chunk.forEach((t,j)=>out.push(localQ(t,j)));}}return out;}
};
